#!/bin/bash

above=$(cd -P .. && pwd -P)

cd ..
mkdir $1
dir=$(cd -P $1 && pwd -P)
cd template

# cp -r .vscode $dir
cp Makefile $dir
cp -r *.code-workspace $dir
cp template.S $dir
cd $dir
mv template.S "$1.S"

sed -i "s/replaceMe/$1/" Makefile

sed -i "s/template/$1/" $1.S
sed -i "s/author/$USER/" $1.S
sed -i "s/system_date_time/$(date)/" $1.S

#!/usr/bin/env bash
cd ../$1
exec bash